export const examList = [
  {
    id: 1,
    name: 'ETS 2022 - TEST 1',
    isExplain: true,
    isTakingExam: true,
    totalPart: 7,
    totalQuestion: 200,
    duration: 120,
    totalComment: 3499,
    numsJoin: 15999,
    hashtags: ['Toeic', 'Reading', 'Listening'],
  },
  {
    id: 2,
    name: 'ETS 2022 - TEST 2',
    isExplain: false,
    totalPart: 7,
    totalQuestion: 200,
    duration: 120,
    totalComment: 3499,
    numsJoin: 15999,
    hashtags: ['Toeic', 'Reading', 'Listening'],
  },
  {
    id: 3,
    name: 'ETS 2022 - TEST 3',
    isExplain: false,
    totalPart: 7,
    totalQuestion: 200,
    duration: 120,
    totalComment: 3499,
    numsJoin: 15999,
    hashtags: ['Toeic', 'Reading', 'Listening'],
  },
  {
    id: 4,
    name: 'ETS 2022 - TEST 4',
    isExplain: false,
    totalPart: 7,
    totalQuestion: 200,
    duration: 120,
    totalComment: 3499,
    numsJoin: 15999,
    hashtags: ['Toeic', 'Reading', 'Listening'],
  },
  {
    id: 5,
    name: 'ETS 2022 - TEST 5',
    isExplain: true,
    totalPart: 7,
    totalQuestion: 200,
    duration: 120,
    totalComment: 3499,
    numsJoin: 15999,
    hashtags: ['Toeic', 'Reading', 'Listening'],
  },
];
