export const MOCK_DATA = [
  {
    name: 'Part 1',
    hashtagList: ['#[Part1] Tranh tả người', '#[Part2] Tranh tả vật'],
  },
  {
    name: 'Part 2',
    hashtagList: [
      '#[Part 2] Câu hỏi 5W1H - what/ which',
      '#[Part 2] Câu hỏi 5W1H - who',
      '#[Part 2] adbsdfsf',
      '#[Part 2] ádaskjdhajksdhakjdh',
      '#[Part 2] abcdefff',
    ],
  },
  {
    name: 'Part 3',
    hashtagList: [
      '#[Part 3] Câu hỏi 5W1H - what/ which',
      '#[Part 3] Câu hỏi 5W1H - who',
      '#[Part 3] adbsdfsf',
      '#[Part 3] ádaskjdhajksdhakjdh',
      '#[Part 3] abcdefff',
      '#[Part 3] Câu hỏi 5W1H - what/ which',
      '#[Part 3] Câu hỏi 5W1H - who',
      '#[Part 3] adbsdfsf',
      '#[Part 3] ádaskjdhajksdhakjdh',
      '#[Part 3] abcdefff',
    ],
  },
  {
    name: 'Part 4',
    hashtagList: [
      '#[Part 4] Câu hỏi 5W1H - what/ which',
      '#[Part 4] Câu hỏi 5W1H - who',
      '#[Part 4] adbsdfsf',
      '#[Part 4] ádaskjdhajksdhakjdh',
      '#[Part 4] abcdefff',
      '#[Part 4] Câu hỏi 5W1H - what/ which',
      '#[Part 4] Câu hỏi 5W1H - who',
      '#[Part 4] adbsdfsf',
      '#[Part 4] ádaskjdhajksdhakjdh',
      '#[Part 4] abcdefff',
    ],
  },
  {
    name: 'Part 5',
    hashtagList: [
      '#[Part 5] Câu hỏi 5W1H - what/ which',
      '#[Part 5] Câu hỏi 5W1H - who',
      '#[Part 5] adbsdfsf',
      '#[Part 5] ádaskjdhajksdhakjdh',
      '#[Part 5] abcdefff',
      '#[Part 5] Câu hỏi 5W1H - what/ which',
      '#[Part 5] Câu hỏi 5W1H - who',
      '#[Part 5] adbsdfsf',
      '#[Part 5] ádaskjdhajksdhakjdh',
      '#[Part 5] abcdefff',
    ],
  },
  {
    name: 'Part 6',
    hashtagList: [
      '#[Part 6] Câu hỏi 5W1H - what/ which',
      '#[Part 6] Câu hỏi 5W1H - who',
      '#[Part 6] adbsdfsf',
      '#[Part 6] ádaskjdhajksdhakjdh',
      '#[Part 6] abcdefff',
      '#[Part 6] Câu hỏi 5W1H - what/ which',
      '#[Part 6] Câu hỏi 5W1H - who',
      '#[Part 6] adbsdfsf',
      '#[Part 6] ádaskjdhajksdhakjdh',
      '#[Part 6] abcdefff',
    ],
  },
  {
    name: 'Part 7',
    hashtagList: [
      '#[Part 7] Câu hỏi 5W1H - what/ which',
      '#[Part 7] Câu hỏi 5W1H - who',
      '#[Part 7] adbsdfsf',
      '#[Part 7] ádaskjdhajksdhakjdh',
      '#[Part 7] abcdefff',
      '#[Part 7] Câu hỏi 5W1H - what/ which',
      '#[Part 7] Câu hỏi 5W1H - who',
      '#[Part 7] adbsdfsf',
      '#[Part 7] ádaskjdhajksdhakjdh',
      '#[Part 7] abcdefff',
    ],
  },
];
